#pragma config(Sensor, dgtl1,  RB,             sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  RF,             sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  LF,             sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  LB,             sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  stat,           sensorTouch)
#pragma config(Motor,  port2,           BLD,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           FLD,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           FRD,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           BRD,           tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void stpl(){//kills drive motors
	motor[FLD] = 0;
	motor[BLD] = 0;
	}
void stpr(){
	motor[FRD] = 0;
	motor[BRD] = 0;}
int kp = 3.2;  // kill switches and constants for PID, do not mess with these
int ki = 1;

int error;
int integral(int in){
	while(true){
		in = in + error;
		return in;
	}
}

int derivative(int err){
	while(true){
		err = error;
		int der = error - err;
		return der;
	}
}
void movefor(int target){
		while(SensorValue[LF] < target && SensorValue[RB] < target){
			int error = target - SensorValue[LF];
			int inte = integral(0);
			if (error == 0){
				inte = 0;}
			if ( abs(error) > 40){
				inte = 0;}
			int deri = derivative(error);
			int speed = (error * kp) + (inte * ki) + deri;
			if(speed > 127){
				int speed = 127;}
			motor[FLD] = speed;
			motor[BLD] = speed;}
		stpl();
		while(SensorValue[RF] < target && SensorValue[LB] < target){
			int error = target - SensorValue[LF];
			int inte = integral(0);
			if (error == 0){
				inte = 0;}
			if ( abs(error) > 40){
				inte = 0;}
			int deri = derivative(error);
			int speed = (error * kp) + (inte * ki) + deri;
			if(speed > 127){
				int speed = 127;}
			motor[FRD] = speed;
			motor[BRD] = speed;}
		stpr();}


void reset(){//resets encoders and gyro based upon what is put in parenthesis
		SensorValue[LF] = 0;
		SensorValue[RF] = 0;
		SensorValue[LB] = 0;
		SensorValue[RB] = 0;}
task main(){
	while(true){
if(SensorValue[stat] == 1){
	reset();
	movefor(200);

}
}
}
