#pragma config(Sensor, in1,    lif,            sensorPotentiometer)
#pragma config(Sensor, dgtl3,  sky,            sensorDigitalOut)
#pragma config(Sensor, dgtl4,  lft,            sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  rig,            sensorQuadEncoder)
#pragma config(Motor,  port1,           FLD,           tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           RLL,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           BRD,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           RRL,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           LLL,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           RightClaw,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           LRL,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LeftClaw,      tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           FRD,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          BLD,           tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////
int x;
int y;

int Userinput(){
	while(true){
		if(nLCDButtons == 1){
			return 1;
			}if(nLCDButtons == 4){
			return 2;
		}
	}
}
void LED(){

	bLCDBacklight = true;
	displayLCDCenteredString(0, "Side?");
	displayLCDString(1, 0, "Red         Blue");
	x = Userinput();
	displayLCDCenteredString(0, "Position?");
	displayLCDString(1, 0, "Left     Right");
	waitInMilliseconds(500);
	y = Userinput();

	if(x == 1 && y == 1){
		displayLCDCenteredString(0, "Re-left, 2 points");}
	if(x == 2 && y == 1){
		displayLCDCenteredString(0, "Blue-left, 2 points");}
	if(x == 1 && y == 2){
		displayLCDCenteredString(0, "Red-Right, 2 points");}
	if(x == 2 && y == 2){
		displayLCDCenteredString(0, "Blue-Right, 2 points");}
}

void pre_auton(){
	if(!bIfiRobotDisabled){ //Allows robot to return to driver mode if cortex experiences a power glitch
		return;
	}
	LED();
	bStopTasksBetweenModes = false;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////
int kp = 2.6;
bool aut = false;
int error;
int integral(int in){
	while(true){
		in = in + error;
		return in;
	}
}
int derivative(int err){
	while(true){
		err = error;
		int der = error - err;
		return der;
	}
}
void lift(string direction, int height){
	if(direction == "up"){
		while(SensorValue[lif] > height){
			motor[RRL] = 127;
			motor[RLL] = 127;
			motor[LLL] = 127;
			motor[LRL] = 127;}
	}
	if(direction == "down"){
		while(SensorValue[lif] < height){
			motor[RRL] = -127;
			motor[RLL] = -127;
			motor[LLL] = -127;
			motor[LRL] = -127;}
	}
	motor[RRL] = 0;
	motor[RLL] = 0;
	motor[LLL] = 0;
	motor[LRL] = 0;
}

void stp(){
	motor[FLD] = 0;
	motor[FRD] = 0;
	motor[BLD] = 0;
	motor[BRD] = 0;}

void reset(string encode){
	if(encode == "lef"){
		SensorValue[lft] = 0;}
	if(encode == "rit"){
		SensorValue[rig] = 0;}
	if(encode == "lif"){
		SensorValue[lif] = 0;}
}

void move(int direction, int target){
	if(direction == 1){
		while(SensorValue[lft] < target){
			int error = target - SensorValue[lft];
			int inte = integral(0);
			if (error == 0){
				inte = 0;}
			if ( abs(error) > 40){
				inte = 0;}
			int deri = derivative(error);
			int speed = (error * kp) + inte + deri;
			if(speed > 127){
				int speed = 127;}
			motor[FLD] = speed;
			motor[FRD] = speed;
			motor[BLD] = speed;
			motor[BRD] = speed;}
		stp();}
}
void movebac(int target){
	while(SensorValue[lft] > target){
		int error = -target + SensorValue[lft];
		int inte = integral(0);
		if (error == 0){
			inte = 0;}
		if (abs(error) > 40){
			inte = 0;}
		int deri = derivative(error);
		int speed = ( error * kp) + inte + deri;
		if(speed > 127){
			int speed = 127;}
		motor[FLD] = -speed;
		motor[FRD] = -speed;
		motor[BLD] = -speed;
		motor[BRD] = -speed;}
	stp();
}


void turn(string direction, int angle){
	if(direction == "R"){
		while(SensorValue[lft] < angle){
			int error = angle - SensorValue[lft];
			int inte = integral(0);
			if (error == 0){
				inte = 0;}
			if ( abs(error) > 40){
				inte = 0;}
			int deri = derivative(error);
			int speed = (error * kp) + inte + deri;
			if(speed > 127){
				int speed = 127;}
			motor[FLD] = speed;
			motor[FRD] = -speed;
			motor[BLD] = speed;
			motor[BRD] = -speed;}
	}
	if(direction == "L"){
		while(SensorValue[lft] > angle){
			int error = -angle + SensorValue[lft];
			int inte = integral(0);
			if (error == 0){
				inte = 0;}
			if ( abs(error) > 40){
				inte = 0;}
			int deri = derivative(error);
			int speed = (error * kp) + inte + deri;
			if(speed > 127){
				int speed = 127;}
			motor[FLD] = -speed;
			motor[FRD] = speed;
			motor[BLD] = -speed;
			motor[BRD] = speed;}
	}
}
void feed(){
	setServo(LeftClaw,120);
	setServo(RightClaw,-120);
}
void close(){
	setServo(RightClaw, -10);
	setServo(LeftClaw, -10);
}
void skygrip(){//puts claws inwards to grab a skyrise
	setServo(LeftClaw, -70);
	setServo(RightClaw,70);}

void fold(){
	setServo(LeftClaw, -120);
	setServo(RightClaw, 120);}

string lef = "lef", rit = "rit", R = "R", L = "L", lfi = "lif", U = "up", Do = "down";
void auto(){
	aut = true;
if(x == 2 && y == 1){
		fold();
		reset(lef);
		movebac(-180);
		feed();
		reset(lef);
		move(1, 260);
		close();
		reset(lef);
		movebac(-40);
		lift(U, 2405);
		reset(lef);
		turn(R, 105);
		reset(lef);
		movebac(-30);
		lift(Do, 3000);
		feed();
		reset(lef);
		movebac(-100);
	}
if(x == 1 && y == 2){
		fold();
		reset(lef);
		movebac(-180);
		feed();
		reset(lef);
		move(1, 290);
		close();
		reset(lef);
		movebac(-90);
		lift(U, 2405);
		reset(lef);
		turn(L, -195);
		reset(lef);
		movebac(-50);
		lift(Do, 3000);
		feed();
		reset(lef);
		movebac(-100);}
if(x == 2 && y == 2){
		reset(lef);
		feed();
		move(1, 250);
		close();
		reset(lef);
		turn(R, 750);
		reset(lef);
		move(1, 100);
		feed();
		reset(lef);
		movebac(-100);}
if(x == 1 && y == 1){
	reset(lef);
		feed();
		move(1, 250);
		close();
		reset(lef);
		turn(L, -650);
		feed();
		reset(lef);
		movebac(-100);}

}
task autonomous(){
	auto();
	aut = false;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

void stahp(){
	motor[RRL] = 0;
	motor[RLL] = 0;
	motor[LLL] = 0;
	motor[LRL] = 0;}

string mainBattery;
int battery2Level;
string expanderbattery;

int precis = 0.7;
void macro(){
	if(vexRT(Btn7D) == 1){
		lift(U, 3080);}
	if(vexRT(Btn8D) == 1){
		lift(U, 3135);}}
task drive(){
	motor[FRD] = vexRT(Ch2)*precis;
	motor[FLD] = vexRT(Ch3)*precis;
	motor[BRD] = vexRT(Ch2)*precis;
	motor[BLD] = vexRT(Ch3)*precis;
	waitInMilliseconds(10);
	motor[FRD] = 0;
	motor[FLD] = 0;
	motor[BRD] = 0;
	motor[BLD] = 0;}
task usercontrol(){
	bLCDBacklight = true;
	while (true){
		if(aut == true){
			stopTask(autonomous);}
			macro();
	precis = vexRT[Btn8DXmtr2] ? 2 : 1;
		startTask(drive);
		clearLCDLine(0);
		clearLCDLine(1);
		//Display the Primary Robot battery voltage
		displayLCDString(0, 0, "Primary: ");
		sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
		displayNextLCDString(mainBattery);

		//Display the Backup battery voltage
		displayLCDString(1, 0, "Expander: ");
		battery2Level = (int)((float)SensorValue[in1] / 275 );
		sprintf(expanderbattery, "%1.2f%c", battery2Level, 'V');
		displayNextLCDString(expanderbattery);
		if(vexRT[Btn8D] == 1){
			SensorValue[sky] = 0;}

		else{
			SensorValue[sky] = 1;}

		if(vexRT(Btn5U) == 1){
			motor[RRL] = 127;
			motor[RLL] = 127;
			motor[LLL] = 127;
			motor[LRL] = 127;
		}
		else if(vexRT(Btn5D) == 1){
			motor[RRL] = -127;
			motor[RLL] = -127;
			motor[LLL] = -127;
			motor[LRL] = -127;
		}
		else{
			stahp();}

		if(vexRT[Btn6U] == 1){
			setServo(LeftClaw,120);
			setServo(RightClaw,-120);}

		else if(vexRT[Btn6D] == 1){
			setServo(LeftClaw, -127);
			setServo(RightClaw,127);}

		else{
			setServo(RightClaw, -10);
			setServo(LeftClaw, -10);}



	}
}
