#pragma config(Motor,  port1,           leftfront,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightfront,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           botlift,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           backright,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           backleft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           toplift,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
	  motor[leftfront] = vexRT(Ch2);
	  motor[backright] = vexRT(Ch2);
	  if(vexRT(Btn7L) == 1){
	  	motor[rightfront] = 127;
	  	motor[backleft] = 127;}
	  if(vexRT(Btn8R) == 1){
	  	motor[rightfront] = -127;
			motor[backleft] = -127;}
		if(vexRT(Btn6U) == 1){
			motor[toplift] = -127;
			motor[botlift] = -127;}
		if(vexRT(Btn6D)== 1){
			motor[toplift] = 127;
			motor[botlift] = 127;}
	}
}
