
#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in1,    lif,            sensorNone)
#pragma config(Sensor, in2,    ritlif,         sensorPotentiometer)
#pragma config(Sensor, in3,    leftLF,         sensorLineFollower)
#pragma config(Sensor, in4,    midLF,          sensorLineFollower)
#pragma config(Sensor, in5,    gyro,           sensorGyro)
#pragma config(Sensor, in6,    rightLF,        sensorLineFollower)
#pragma config(Sensor, in7,    accel,          sensorAccelerometer)
#pragma config(Sensor, dgtl3,  sky,            sensorDigitalOut)
#pragma config(Sensor, dgtl4,  rig,            sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  lft,            sensorQuadEncoder)
#pragma config(Motor,  port1,           FLD,           tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           RLL,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           BRD,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           RRL,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           LLL,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           RightClaw,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           LRL,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LeftClaw,      tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           FRD,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          BLD,           tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings


int kp = 1.3;
int ki = 1;
bool aut = false;
int error;
int integral(int in){
	while(true){
		in = in + error;
		return in;
	}
}

int derivative(int err){
	while(true){
		err = error;
		int der = error - err;
		return der;
	}
}
void lift(string direction, int rheight, int lheight){// decently self explanatory, it either goes up or down according to the
	//right potentiometer height and left potentiometer height, with left being negative
	if(direction == "up"){
		while(SensorValue[ritlif] < rheight){
			motor[RRL] = 127;
			motor[RLL] = 127;}

		while(SensorValue[lif] > lheight){
			motor[LLL] = 127;
			motor[LRL] = 127;}
}
	if(direction == "down"){
		while(SensorValue[ritlif] > rheight){
			motor[RRL] = -127;
			motor[RLL] = -127;}
		while(SensorValue[lif] < lheight){
			motor[LLL] = -127;
			motor[LRL] = -127;}
	}
	motor[RRL] = 0;
	motor[RLL] = 0;
	motor[LLL] = 0;
	motor[LRL] = 0;
}

void stp(){//kills drive motors
	motor[FLD] = 0;
	motor[FRD] = 0;
	motor[BLD] = 0;
	motor[BRD] = 0;}

void reset(string encode){//resets encoders and gyro based upon what is put in parenthesis
	if(encode == "lef"){
		SensorValue[lft] = 0;}
	if(encode == "rit"){
		SensorValue[rig] = 0;}
	if(encode == "lif"){
		SensorValue[lif] = 0;}
	if(encode == "giro"){
		SensorValue[gyro] = 1;}
}
//error, inte, deri, and speed are all part of PID
void move(int direction, int target){//standard forward movement
	if(direction == 1){
		while(SensorValue[lft] < target){
			int error = target - SensorValue[lft];
			int inte = integral(0);
			if (error == 0){
				inte = 0;}
			if ( abs(error) > 40){
				inte = 0;}
			int deri = derivative(error);
			int speed = (error * kp) + (inte * ki) + deri;
			if(speed > 127){
				speed = 127;}
			if(error < 60){
				motor[FLD] = (speed*2);
				motor[FRD] = (speed*2);
				motor[BLD] = (speed*2);
				motor[BRD] = (speed*2);}
			else{
			motor[FLD] = speed;
			motor[FRD] = speed;
			motor[BLD] = speed;
			motor[BRD] = speed;}
			}
		stp();}
}
void movebac(int target){//standard movement back, target int is distance travelled, positive
	while(SensorValue[lft] > target){
		int error = SensorValue[lft] - target;
		int inte = integral(0);
		if (error == 0){
			inte = 0;}
		if (abs(error) > 40){
			inte = 0;}
		int deri = derivative(error);
		int speed = ( error * kp) + (inte * ki) + deri;
		if(speed > 127){
			speed = 127;}
		if(error < 60){
			motor[FLD] = (-speed*2);
			motor[FRD] =(-speed*2);
			motor[BLD] =(-speed*2);
			motor[BRD] =(-speed*2);}
		else{
		motor[FLD] = -speed;
		motor[FRD] = -speed;
		motor[BLD] = -speed;
		motor[BRD] = -speed;}}
	stp();
}
//don't worry about the music

void turn(string direction, int angle){// turn function, L is left turn with a positive desired turn and R is right and
	//negative
	if(direction == "L"){
		while(SensorValue[gyro] < angle){
			int error = angle - SensorValue[lft];
			int inte = integral(0);
			while (error < 0){
				error = -error;}
			if (error == 0){
				inte = 0;}
			if ( abs(error) > 40){
				inte = 0;}
			int deri = derivative(error);
			int speed = (error * kp) + (inte * ki) + deri;
			if(speed > 127){
				speed = 127;}
			if(error < 60){
				motor[FLD] = -(speed*2);
				motor[FRD] = (speed*2);
				motor[BLD] = -(speed*2);
				motor[BRD] = (speed*2);}
			else{
			motor[FLD] = -(speed);
			motor[FRD] = (speed);
			motor[BLD] = -(speed);
			motor[BRD] = (speed);}
		}
	}
	if(direction == "R"){
		while(SensorValue[gyro] > angle){
			int error = SensorValue[lft] - angle;
			int inte = integral(0);
			while (error < 0){
				error = -error;}
			if (error == 0){
				inte = 0;}
			if ( abs(error) > 40){
				inte = 0;}
			int deri = derivative(error);
			int speed = (error * kp) + (inte * ki) + deri;
			if(speed > 127){
				speed = 127;}
			if(error < 60){
				motor[FLD] = (speed*3);
				motor[FRD] = -(speed*3);
				motor[BLD] = (speed*3);
				motor[BRD] = -(speed*3);}
			else{
			motor[FLD] = (speed*2);
			motor[FRD] = -(speed*2);
			motor[BLD] = (speed*2);
			motor[BRD] = -(speed*2);}}
	}
stp();
}
void swinturn(string direction, int angle, int forw){// turn function, L is left turn with a positive desired turn and R is right and
	//negative
	if(direction == "L" && forw == 0){
		while(SensorValue[gyro] < angle){
			int error = angle - SensorValue[lft];
			int inte = integral(0);
			while (error < 0){
				error = -error;}
			if (error == 0){
				inte = 0;}
			if ( abs(error) > 40){
				inte = 0;}
			int deri = derivative(error);
			int speed = (error * kp) + (inte * ki) + deri;
			if(speed > 127){
				speed = 127;}
			if(error < 50){
				motor[FLD] = -(speed*1.35);
				motor[BLD] = -(speed*1.35);}
			else{
			motor[FLD] = -(1.4*speed);
			motor[BLD] = -(1.4*speed);}
			}
	}
		if(direction == "L" && forw == 1){
		while(SensorValue[gyro] < angle){
			int error = angle - SensorValue[lft];
			int inte = integral(0);
			while (error < 0){
				error = -error;}
			if (error == 0){
				inte = 0;}
			if ( abs(error) > 40){
				inte = 0;}
			int deri = derivative(error);
			int speed = (error * kp) + (inte * ki) + deri;
			if(speed > 127){
				speed = 127;}
			if(error < 60){
				motor[FRD] = (speed*2);
				motor[BRD] = (speed*2);}
			else{
			motor[FRD] = (speed);
			motor[BRD] = (speed);}
			}
	}
	if(direction == "R" && forw == 0){
		while(SensorValue[gyro] > angle){
			int error =  SensorValue[lft] - angle;
			int inte = integral(0);
			while (error < 0){
				error = -error;}
			if (error == 0){
				inte = 0;}
			if ( abs(error) > 40){
				inte = 0;}
			int deri = derivative(error);
			int speed = (error * kp) + (inte * ki) + deri;
			if(speed > 127){
				speed = 127;}
			if(error < 60){
				motor[FRD] = -(speed*2);
				motor[BRD] = -(speed*2);}
			else{
			motor[FRD] = -(speed);
			motor[BRD] = -(speed);}
			}
	}
	if(direction == "R" && forw == 1){
		while(SensorValue[gyro] > angle){
			int error = SensorValue[lft] - angle;
			int inte = integral(0);
			while (error < 0){
				error = -error;}
			if (error == 0){
				inte = 0;}
			if ( abs(error) > 40){
				inte = 0;}
			int deri = derivative(error);
			int speed = (error * kp) + (inte * ki) + deri;
			if(speed > 127){
				speed = 127;}
			if(error < 60){
				motor[FLD] = (speed*2);
				motor[BLD] = (speed*2);}
			else{
			motor[FLD] = (speed);
			motor[BLD] = (speed);}}
	}
stp();
}

void feed(){//opens claws
	setServo(LeftClaw,120);
	setServo(RightClaw,-120);
}
void close(){//puts claws in starting postion
	setServo(RightClaw, -30);
	setServo(LeftClaw, -10);
}
void skygrip(){//puts claws inwards to grab a skyrise
	setServo(LeftClaw, -70);
	setServo(RightClaw,40);}

void fold(){
	setServo(LeftClaw, -120);
	setServo(RightClaw, 120);}

string lef = "lef", rit = "rit", R = "R", L = "L", lfi = "lif", U = "up", Do = "down", giro = "giro";
task main()
{
reset(giro);
turn(R,-49);
reset(giro);
turn(L, 542);
reset(giro);
turn(L, 1597);
reset(giro);
lift(U,816,3096);
feed();
skygrip();
close();
turn(L, 1390);
reset(giro);
turn(R,-14);
reset(giro);


}
