#pragma config(Sensor, dgtl4,  lif,            sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  lef,            sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  rig,            sensorQuadEncoder)
#pragma config(Motor,  port1,           liftleft,      tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           backright,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           frontright,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           liftleft2,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           RightClaw,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port6,           LeftClaw,      tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           liftright2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           liftright,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           backleft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          frontleft,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
if(!bIfiRobotDisabled){ //Allows robot to return to driver mode if cortex experiences a power glitch
    return;
   }
bStopTasksBetweenModes = true;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

void movet(int dis){
	motor[frontleft] = 127;
	motor[backleft] = 127;
	motor[frontright] = 127;
	motor[backright] = 127;
	waitInMilliseconds(dis);
	motor[frontleft] = 0;
	motor[backleft] = 0;
	motor[frontright] = 0;
	motor[backright] = 0;}
void movetb(int dis){
	motor[frontleft] = -127;
	motor[backleft] = -127;
	motor[frontright] = -127;
	motor[backright] = -127;
	waitInMilliseconds(dis);
	motor[frontleft] = 0;
	motor[backleft] = 0;
	motor[frontright] = 0;
	motor[backright] = 0;}

string lft = "lef";


task autonomous()
{
	waitInMilliseconds(500);
	movetb(500);
	waitInMilliseconds(500);
	movet(500);


}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////
void lift(string direction){
	if (direction == "up"){
		motor[liftleft] = (127*(0.9));
		motor[liftright] = (127*(0.9));
		motor[liftleft2] = (127*(0.9));
		motor[liftright2] = (127*(0.9));
		waitInMilliseconds(10);
		stopMotor(liftleft);
		stopMotor(liftright);
		stopMotor(liftleft2);
		stopMotor(liftright2);}
	if (direction == "down"){
		motor[liftleft] = (-127*(0.9));
		motor[liftright] = (-127*(0.9));
		motor[liftleft2] = (-127*(0.9));
		motor[liftright2] = (-127*(0.9));
		waitInMilliseconds(10);
		stopMotor(liftleft);
		stopMotor(liftright);
		stopMotor(liftleft2);
		stopMotor(liftright2);}
}
string up = "up", down = "down";
task usercontrol()
{
	while (true)
	{
		motor[frontleft] = vexRT(Ch3);
		motor[backleft] = vexRT(Ch3);
		motor[frontright] = vexRT(Ch2);
		motor[backright] = vexRT(Ch2);
		waitInMilliseconds(10);
		stopMotor(frontleft);
		stopMotor(backleft);
		stopMotor(frontright);
		stopMotor(backright);

		if(vexRT(Btn6U) == 1){
			lift(up);}

		if(vexRT(Btn6D) == 1){
			lift(down);}

		if(vexRT[Btn5U] == 1){
			setServo(LeftClaw, 127);
			setServo(RightClaw, -127);}

		else if(vexRT[Btn5D] == 1){////////////////////////////claw//////////////////////
			setServo(LeftClaw, -120);
			setServo(RightClaw,120);}

		else{
			setServo(RightClaw, 0);
			setServo(LeftClaw, 0);}
	}

}
