#pragma config(Sensor, dgtl1,  skygrip,        sensorDigitalOut)
#pragma config(Motor,  port2,           botbaselift,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           topbaselift,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           armrotate,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
while(true){
 motor[botbaselift] = (vexRT(Ch3) * 0.8);
 motor[topbaselift] = (vexRT(Ch3) * 0.8);
 motor[armrotate] = -(vexRT(Ch2)* 0.8);
	if(vexRT(Btn6U) == 1){
		SensorValue[skygrip] = 1;}
	else{
		SensorValue[skygrip] = 0;}

	}
}
