#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, dgtl1,  skygrip,        sensorDigitalOut)
#pragma config(Motor,  port1,           leftdrive,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           botbaselift,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           armrotate,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           TLL,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           BLL,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           TRL,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           BRL,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,     rightdrive,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           claw,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          topbaselift,   tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////
  int x;
int y;
int Userinput(){
	while(true){
		if(nLCDButtons == 1){
			return 1;
			}if(nLCDButtons == 4){
			return 2;
		}
	}
}

void LED(){

	bLCDBacklight = true;
	displayLCDCenteredString(0, "Side?");
	displayLCDString(1, 0, "Red         Blue");
	x = Userinput();
	displayLCDCenteredString(0, "Position?");
	displayLCDString(1, 0, "Left       Right");
	waitInMilliseconds(500);
	y = Userinput();
}

void pre_auton(){

	if(!bIfiRobotDisabled){ //Allows robot to return to driver mode if cortex experiences a power glitch
		return;
	}
	LED();
	bStopTasksBetweenModes = false;}


/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////
bool direction;
bool swich(){
	if(vexRT(Btn8U) == 1){
 		direction = true;}
 	else{
 		direction = false;}
 	return direction;}
task usercontrol()
{
	while (true)
	{
	  motor[botbaselift] = (vexRT(Ch3) * 0.8);
 		motor[topbaselift] = (vexRT(Ch3) * 0.8);
 	swich();
 	if(direction == false){
 		motor[armrotate] = -(vexRT(Ch2)* 0.8);}
 	if(direction == true){
 		motor[armrotate] = (vexRT(Ch2)* 0.8);}
		if(vexRT(Btn6U) == 1){
			SensorValue[skygrip] = 1;}
		else{
			SensorValue[skygrip] = 0;}
		motor[leftdrive] = vexRT(Ch3Xmtr2);
		motor[rightdrive] = vexRT(Ch2Xmtr2);
		if(vexRT(Btn5UXmtr2) == 1){
			motor[TRL] = 127*0.5;
			motor[BRL] = 127*0.5;
			motor[TLL] = 127*0.5;
			motor[BLL] = 127*0.5;}
		else if(vexRT(Btn5DXmtr2) == 1){
			motor[TRL] = -127*.5;
			motor[BRL] = -127*.5;
			motor[TLL] = -127*.5;
			motor[BLL] = -127*.5;}
		else{
			motor[TRL] = 0;
			motor[BRL] = 0;
			motor[TLL] = 0;
			motor[BLL] = 0;}
		if(vexRT(Btn6UXmtr2) == 1){
			motor[claw] = 127*0.3;}
		else if(vexRT(Btn6DXmtr2) == 1){
			motor[claw] = -127*0.3;}
		else{
			motor[claw] = 0;}

	}
}
