#pragma config(Motor,  port1,           botright,      tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           topleft,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           Lift1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Lift2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           topright,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          botleft,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	while(true){
		startMotor(botleft, vexRT(Ch3));
		startMotor(botright, vexRT(Ch2));
		startMotor(topleft, vexRT(Ch3));
		startMotor(topright, vexRT(Ch2));
		waitInMilliseconds(10);
		stopMotor(topleft);
		stopMotor(topright);
		stopMotor(botleft);
		stopMotor(botright);

		if(vexRT(Btn6U) == 1){
			motor[Lift1] = (127*0.6);
			motor[Lift2] = (127*0.6);
			waitInMilliseconds(10);
			motor[Lift1] = 0;
			motor[Lift2] = 0;}

		if(vexRT(Btn6D) == 1){
			motor[Lift1] = (-127 * 0.8);
			motor[Lift2] = (-127 * 0.8);
			waitInMilliseconds(10);
			motor[Lift1] = 0;
			motor[Lift2] = 0;}

	}
}
