#pragma config(Motor,  port1,           topleft,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           topright,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           bottomright,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           bottomleft,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	while(true){
		if(vexRT(Btn6D) == 1){
			motor[topleft] = -127;
			motor[bottomleft] = -127;
			motor[topright] = -127;
			motor[bottomright] = -127;
			waitInMilliseconds(10);
			motor[topleft] = 0;
			motor[bottomleft] = 0;
			motor[topright] = 0;
			motor[bottomright] = 0;}
		if(vexRT(Btn6U) == 1){
			motor[topleft] = 127;
			motor[bottomleft] = 127;
			motor[topright] = 127;
			motor[bottomright] = 127;
			waitInMilliseconds(10);
			motor[topleft] = 0;
			motor[bottomleft] = 0;
			motor[topright] = 0;
			motor[bottomright] = 0;}
}
}
