#pragma config(Sensor, dgtl1,  cat,            sensorDigitalOut)
#pragma config(Motor,  port1,           frd,           tmotorVex393, openLoop)
#pragma config(Motor,  port2,           fld,           tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           brd,           tmotorVex393, openLoop)
#pragma config(Motor,  port4,           bld,           tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	  while(vexRT(Btn6U) == 0)


		if(vexRT(Btn6U) == 1){
		startMotor(frd, -127);
		startMotor(fld, -127);
		startMotor(brd, -127);
		startMotor(bld, -127);
		waitInMilliseconds(250);
		stopMotor(frd);
		stopMotor(fld);
		stopMotor(brd);
		stopMotor(bld);
		SensorValue(cat) = 1;}


}
