#pragma config(Sensor, in1,    lif,            sensorPotentiometer)
#pragma config(Sensor, in2,    ritlif,         sensorPotentiometer)
#pragma config(Sensor, dgtl3,  sky,            sensorDigitalOut)
#pragma config(Sensor, dgtl4,  rig,            sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  lft,            sensorQuadEncoder)
#pragma config(Motor,  port1,           FLD,           tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           RLL,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           BRD,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           RRL,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           LLL,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           RightClaw,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           LRL,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LeftClaw,      tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           FRD,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          BLD,           tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define spinJoy Ch1
#define fwdJoy Ch3

task main(){
	char encoderVal[15];
	bool fwd = false;
	bool bwd = false;
	bool fwdJoyTog = false;
	bool spinJoyTog = false;
	bool leftSpin = false;
	bool rightSpin = false;
	bool armTog = false;
	bool upArm = false;
	bool downArm = false;
	bool close = false;
	bool intakePrintTog = false;
	clearDebugStream();
	while(true){


		if (vexRT[Btn7U] == 1)
		{
			clearDebugStream();
		}

			if (vexRT[fwdJoy] >= 15)//Adds a thershhold of +10 to set values
			{
				//so if someone is pushing the fwdJoy in the possitive y direction, turn all of these vars to these states
				fwdJoyTog = true;
				fwd = true;
				motor[BRD] = vexRT(Ch3);
				motor[FRD] = vexRT(Ch3);
				motor[BLD] = vexRT(Ch3);
				motor[FLD] = vexRT(Ch3);
			}
			//seeing if the joy is being pushed in the negative y direction, meaning the bot should go backwards
			else if (vexRT[fwdJoy] <= -15)//Adds a thershhold of -10 to set values
			{
				motor[BRD] = vexRT(Ch3);
				motor[FRD] = vexRT(Ch3);
				motor[BLD] = vexRT(Ch3);
				motor[FLD] = vexRT(Ch3);
				fwdJoyTog = true;
				bwd = true;
			}
			//If the fwdJoy is not being touched, then check all this:
			else
			{
				if (fwdJoyTog == false)//if there is no input to the fwdJoy,
				{
					if(spinJoyTog == false)//if there is no input to the spinJoy,
					{
						SensorValue[lft] = 0; //clear the encoder on the front wheel(which is used for all encoder values)
						//when the bot isnt moving, basically  resetting the bot for the next move.
						//The reason for this is to make sure that while youre trying to spin the bot, the code isnt clearing the encoder
						//because its all like "Oh hey, no one is trying to move forward so I better clear the encoder" which is the same
						//encoder the spin is using to record its turn. Which would result in 0 being pritned out over and over again.
						//*Skip this next explination unless you have a good grasp on what is going on, it's not critical*
						//(If you really get into the code you'll realise that the spin is done with a gyro instead of a encoder, but
						//it used to be done with the same encoder, and could be swiched back to one if your team does not own a gyro
						//(which i would really recomend you get one, they are amazing). So yeah it is possible to do without a gyro.)
					}
					}else{//This is an else statment to the first if statement above: 	if (fwdJoyTog == false)
					//so if fwdJoyTog is true, which got changed to true if the fwdjoy was moving in the positive or negative
					//Y direction, see above (line ~167 & 176).

					//so an important note here is that the only way the code will get to the above else statement, is if the if on line 164
					//and the else if on line 174 evalutate to be false. So basically while the fwdJoy is being pushed forward, the code stays in
					//the if on line 164 and writes the power to the bot (bottom of the code) so that it moves forward.
					//So then when you return the fwdJoy to 0, the code goes to the else on line 181, but the if on line 183 evaluates to be
					//false, since fwdJoyTog is still true from the if on line 164, bringing us here to this else. So this code will
					//only activate once per movement, since fwdJoyTog gets reset to false at the end of this code. So this is the code
					//that prints the last movement to the debugstream. And the next loop through the code goes to line 189, resetting the
					//encoder for the next move. Thus, the next time you move fwdJoy the bot will move, causing the encoder to count,
					//and that value will get printed out using the code below. And the cycle continues indefinatly.
					if (fwd == true)// meaning the bot went forward
								{
									//so we conver our current encoder value and power values from ints to strings and store them in our
									//char arrays that we declared at the top of the code.
									sprintf(encoderVal, "%d", abs(SensorValue[lft]));
										writeDebugStream("move(1, ");
										writeDebugStream(encoderVal);
										writeDebugStreamLine(");");
						fwd = false;
						fwdJoyTog = false;
						}else{

						//if fwd = false, then it must be going backwards. So here is the same code, just using backwardFour instead of ForwardFour
						sprintf(encoderVal, "%d", abs(SensorValue[lft]));
						writeDebugStream("move(0, ");
						writeDebugStream(encoderVal);
						writeDebugStreamLine(");");
						bwd = false;
						fwdJoyTog = false;
				}
			}
		}
	}
			//Setting variables for Spin
		if (vexRT[spinJoy] >= 10)
		{
			spinJoyTog = true;
			rightSpin = true;
			motor[BRD] = -vexRT(Ch1);
			motor[FRD] = -vexRT(Ch1);
			motor[BLD] = vexRT(Ch1);
			motor[FLD] = vexRT(Ch1);

		}
		else if(vexRT[spinJoy] <= -10)
		{
			spinJoyTog = true;
			leftSpin = true;
			motor[BRD] = vexRT(Ch1);
			motor[FRD] = vexRT(Ch1);
			motor[BLD] = -vexRT(Ch1);
			motor[FLD] = -vexRT(Ch1);
		}
		else
		{
			if (spinJoyTog == false)
			{
			if(fwdJoyTog == false)
				{

					SensorValue[lft] = 0;
				}
			}else{
					if (rightSpin == true)// meaning the bot went right
					{
						sprintf(encoderVal, "%d", abs(SensorValue[lft]));
						writeDebugStream("turn(R");
						writeDebugStream(",");
						writeDebugStream(encoderVal);
						writeDebugStreamLine(");");
						rightSpin = false;
						spinJoyTog = false;
					}else{
						sprintf(encoderVal, "%d", abs(SensorValue[rig]));
						writeDebugStream("turn(L");
						writeDebugStream(",");
						writeDebugStream(encoderVal);
						writeDebugStreamLine(");");
						leftSpin = false;
						spinJoyTog = false;
				}
			}
	}
	if (vexRT[Btn6U]== 1 && vexRT[Btn6D]== 0 )//Checks for single button press
		{
			armTog = true;
			upArm = true;
			motor[RRL] = 127;
			motor[RLL] = 127;
			motor[LLL] = 127;
			motor[LRL] = 127;}
	else if (vexRT[Btn6U]== 0 && vexRT[Btn6D]== 1  )//Checks for single button press
		{
			armTog = true;
			downArm = true;
			motor[RRL] = -127;
			motor[RLL] = -127;
			motor[LLL] = -127;
			motor[LRL] = -127;}
	else{
			if(armTog == false)
			{	}
			else{
				if(upArm == true)
				{
						sprintf(encoderVal, "%d", abs(SensorValue[lif]));
						writeDebugStream("lift(U");
						writeDebugStream(",");
						writeDebugStream(encoderVal);
						writeDebugStreamLine(");");
						upArm = false;
						armTog = false;
					}else{
						sprintf(encoderVal, "%d", abs(SensorValue[lif]));
						writeDebugStream("lift(D");
						writeDebugStream(",");
						writeDebugStream(encoderVal);
						writeDebugStreamLine(");");
						downArm = false;
						armTog = false;
				}
			}
		}
		if (vexRT[Btn5U]== 1 && vexRT[Btn5D]== 0 )//Checks for single button press
		{
			setServo(LeftClaw,120);
			setServo(RightClaw,-120);
			intakePrintTog = true;
	}
	else if(vexRT[Btn5U] == 0 && vexRT[Btn5D] == 1)
	{			setServo(RightClaw, -10);
				setServo(LeftClaw, -10);
				close = true;}

	if(intakePrintTog == true)
			{
				writeDebugStream("feed(); ");
				intakePrintTog = false;
			}
	if(close == true){
		writeDebugStream("close(); ");
		close = false;
	}
}
