#pragma config(Sensor, dgtl1,  distance,       sensorSONAR_inch)
#pragma config(Motor,  port1,           motor1,        tmotorVex393, openLoop)
#pragma config(Motor,  port2,           motor2,        tmotorVex393, openLoop)
#pragma config(Motor,  port3,           motor3,        tmotorVex393, openLoop)
#pragma config(Motor,  port10,          motor4,        tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	while(true){
			motor[motor1] = 127;
			motor[motor2] = 127;
			motor[motor3] = 127;
			motor[motor4] = 127;}
	}
