#pragma config(Motor,  port1,           rfd,           tmotorVex393, openLoop)
#pragma config(Motor,  port2,           lfd,           tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           rbd,           tmotorVex393, openLoop)
#pragma config(Motor,  port4,           lbd,           tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           rbl,           tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           lbl,           tmotorVex393, openLoop)
#pragma config(Motor,  port7,           rtl,           tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           ltl,           tmotorVex393, openLoop)
#pragma config(Motor,  port9,           feedl,         tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port10,          feedr,         tmotorVex269, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void feedmovement(string vac, string direction, int go){
	if(direction == "forward"){
		motor[rfd] = 127;
		motor[rbd] = 127;
		motor[lfd] = 127;
		motor[lbd] = 127;
		waitInMilliseconds(go);
		motor[rfd] = 0;
		motor[rbd] = 0;
		motor[lfd] = 0;
		motor[lbd] = 0;}
	if(direction == "back"){
		motor[rfd] = -127;
		motor[rbd] = -127;
		motor[lfd] = -127;
		motor[lbd] = -127;
		waitInMilliseconds(go);
		motor[rfd] = 0;
		motor[rbd] = 0;
		motor[lfd] = 0;
		motor[lbd] = 0;}
	if(vac == "in"){
		motor[feedl] = 127;
		motor[feedr] = 127;
		waitInMilliseconds(go);
		motor[feedl] = 0;
		motor[feedr] = 0;}
	if(vac == "out"){
		motor[feedl] = -127;
		motor[feedr] = -127;
		waitInMilliseconds(go);
		motor[feedl] = 0;
		motor[feedr] = 0;}
	if(vac == "no"){
		motor[feedl] = 0;
		motor[feedr] = 0;}
}
	void feed(int go, string direction){
		if(direction == "ahead"){
			motor[feedl] = 127;
			motor[feedr] = 127;
			waitInMilliseconds(go);
			motor[feedl] = 0;
			motor[feedr] = 0;}
		if(direction == "back"){
			motor[feedl] = -127;
			motor[feedr] = -127;
			waitInMilliseconds(go);
			motor[feedl] = 0;
			motor[feedr] = 0;}
	}


task main(){}
