#pragma config(Motor,  port7,           LM,            tmotorVex393, openLoop)
#pragma config(Motor,  port8,           RM,            tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	while(true){
		waitInMilliseconds(10);
		if(vexRT(AccelY) > 2){
			startMotor(LM, 127);
			startMotor(RM, 127);}
		if(vexRT(AccelY) < -2){
			startMotor(LM, -127);
			startMotor(RM, -127);}
	}
}
