#pragma config(Sensor, dgtl1,  lft,            sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rig,            sensorQuadEncoder)
#pragma config(Motor,  port1,           frontleft,     tmotorVex269_HBridge, openLoop)
#pragma config(Motor,  port2,           frontright,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           backright,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port4,           backleft,      tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port8,           toplift,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           botlift,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task normalstrafe {

		if(vexRT(Btn5D) == 1){
			motor[frontleft] = -127;
			motor[frontright] = -127;
			motor[backleft] = 127;
			motor[backright] = 127;}
		if(vexRT(Btn6D) == 1){
			motor[frontleft] = 127;
			motor[frontright] = 127;
			motor[backleft] = -127;
			motor[backright] = -127;}
	}
void drive(){
	motor[frontleft] = (vexRT(Ch3) + -vexRT(Ch2));
	motor[frontright] = (-vexRT(Ch3) + -vexRT(Ch2));
	motor[backleft] = (vexRT(Ch3) + -vexRT(Ch2));
	motor[backright] = (-vexRT(Ch3) + -vexRT(Ch2));}
task main(){
	while(true){
		if(vexRT(Btn7U) == 0){
			startTask(normalstrafe);
			drive();}

		if(vexRT(Btn7U) == 1){
			drive();}

		if(vexRT(Btn7L) == 1){
			while(SensorValue(lft) < 100){
				motor[frontleft] = 100;
				motor[frontright] = 100;
				motor[backleft] = 100;
				motor[backright] = 100;}}

		if(vexRT(Btn6U) == 1){
			motor[toplift] = 127* 0.9;
			motor[botlift] = 127* 0.9;
			waitInMilliseconds(10);
			motor[toplift] = 0;
			motor[botlift] = 0;}


	}
}
