#pragma config(Motor,  port1,           rightbotlift,  tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           righttoplift,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftbotlift,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          lefttoplift,   tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
while(true){
	if(vexRT(Btn6U) == 1){
		motor[rightbotlift] = 127;
		motor[righttoplift] = 127;
		motor[leftbotlift] = 127;
		motor[lefttoplift] = 127;
		waitInMilliseconds(10);
		motor[rightbotlift] = 0;
		motor[righttoplift] = 0;
		motor[leftbotlift] = 0;
		motor[lefttoplift] = 0;}
	if(vexRT(Btn6D) == 1){
		motor[rightbotlift] = -127;
		motor[righttoplift] = -127;
		motor[leftbotlift] = -127;
		motor[lefttoplift] = -127;
		waitInMilliseconds(10);
		motor[rightbotlift] = 0;
		motor[righttoplift] = 0;
		motor[leftbotlift] = 0;
		motor[lefttoplift] = 0;}
}
}
