#pragma config(Motor,  port1,           DriveRight,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           LiftLeft,      tmotorVex393, openLoop)
#pragma config(Motor,  port5,           LiftRight,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port10,          DriveLeft,     tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){

		startMotor (DriveLeft, vexRT(Ch3));
		startMotor (DriveRight, vexRT(Ch2));
		waitInMilliseconds (10);
		stopMotor (DriveLeft);
		stopMotor (DriveRight);

		if(vexRT(Btn6U) == 1) {
			startMotor(LiftLeft, 127);
			startMotor(LiftRight, 127);
			waitInMilliseconds (10);
			stopMotor(LiftLeft);
			stopMotor(LiftRight);}

		if(vexRT(Btn6D) == 1) {
			startMotor(LiftLeft, -127);
			startMotor(LiftRight, -127);
			waitInMilliseconds (10);
			stopMotor(LiftLeft);
			stopMotor(LiftRight);}



	}

}
