#pragma config(Motor,  port2,           RightMotor,    tmotorVex393, openLoop)
#pragma config(Motor,  port3,           FrontLeft,     tmotorVex393, openLoop)
#pragma config(Motor,  port4,           FrontRight,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           LeftMotor,     tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(true){

	if(vexRT(Btn6D) == 1) {
		startMotor (FrontLeft, 117);
		startMotor (FrontRight, 127);
		waitInMilliseconds (10);
		stopMotor (FrontLeft);
		stopMotor (FrontRight);}

	if(vexRT(Btn6U) == 1) {
		startMotor (FrontLeft, -117);
		startMotor (FrontRight, -127);
		waitInMilliseconds (10);
		stopMotor (FrontLeft);
		stopMotor (FrontRight);}

	startMotor (LeftMotor, vexRT(Ch3));
	startMotor (RightMotor, vexRT(Ch2));
	waitInMilliseconds (10);
	stopMotor (RightMotor);
	stopMotor (LeftMotor) ;
}


}
