#pragma config(Motor,  port1,           FRD,           tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           BRD,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           BRL,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           TRL,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           IN1,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           IN2,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           TLL,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           BLL,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           BLD,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          FLD,           tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{

	bStopTasksBetweenModes = true;


}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{


	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

void stahp(){
	motor[TLL] = 0;
	motor[BLL] = 0;
	motor[BRL] = 0;
	motor[TRL] = 0;}

void stahpfeed(){
	motor[IN1] = 0;
	motor[IN2] = 0;}

task usercontrol()
{

	while (true)
	{
		motor[FRD] = vexRT(Ch3) - vexRT(Ch1);
		motor[FLD] = vexRT(Ch3) + vexRT(Ch1);
		motor[BRD] = vexRT(Ch3) - vexRT(Ch1);
		motor[BLD] = vexRT(Ch3) + vexRT(Ch1);
		waitInMilliseconds(10);
		motor[FRD] = 0;
		motor[FLD] = 0;
		motor[BRD] = 0;
		motor[BLD] = 0;

		if(vexRT(Btn6U) == 1){
			motor[TLL] = 127;
			motor[BLL] = 127;
			motor[BRL] = 127;
			motor[TRL] = 127;
			}
		else if(vexRT(Btn6D) == 1){
			motor[TLL] = -127;
			motor[BLL] = -127;
			motor[BRL] = -127;
			motor[TRL] = -127;
			}
		else{
			stahp();}


		if(vexRT(Btn5U) == 1){
			motor[IN1] = 127;
			motor[IN2] = 127;
			}
		else if(vexRT(Btn5D) == 1){
			motor[IN1] = -127;
			motor[IN2] = -127;
		}
		else{
			stahpfeed();}


	}
}
