#pragma config(Sensor, dgtl1,  lft,            sensorQuadEncoder)
#pragma config(Motor,  port1,           FR,            tmotorVex269_HBridge, openLoop)
#pragma config(Motor,  port7,           BL,            tmotorServoContinuousRotation, openLoop, driveLeft, encoderPort, dgtl1)
#pragma config(Motor,  port8,           BR,            tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          FL,            tmotorVex269_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton(){

	bStopTasksBetweenModes = false;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

int error;
 int integral(int in){
	while(true){
		in = in + error;
		return in;
	}
}

int derivative(int err){
	while(true){
		err = error;
		int der = error - err;
		return der;
	}
}




void stahp(){
		motor[FL] = 0;
		motor[FR] = 0;
		motor[BL] = 0;
		motor[BR] = 0;}

void reset(string encode){
	if(encode == "lef"){
		SensorValue(lft) = 0;}
}



void movefor(int target){
	while(SensorValue[lft] < target){
		int error = target - SensorValue[lft];
		int inte = integral(0);
		if (error == 0)
		{
		inte = 0;
		}
		if ( abs(error) > 40)
		{
		inte = 0;
		}
		int deri = derivative(error);

		int speed = error + inte + deri;
		if(speed > 127){
			int speed = 127;}

		motor[FL] = speed;
		motor[FR] = speed;
		motor[BL] = speed;
		motor[BR] = speed;
		}
	stahp();}

string lef = "lef";

void auto(){

		reset(lef);
		movefor(1000);

}

task autonomous()
{

	auto();

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////


task usercontrol()
{

	while (true)
	{
		motor[FL] = vexRT(Ch3);
		motor[BL] = vexRT(Ch3);
		motor[BR] = vexRT(Ch2);
		motor[FR] = vexRT(Ch2);

	}
}
