#pragma config(Sensor, in1,    dial,           sensorPotentiometer)
#pragma config(Sensor, dgtl1,  lft,            sensorQuadEncoder)
#pragma config(Motor,  port1,           FR,            tmotorVex269_HBridge, openLoop)
#pragma config(Motor,  port7,           BL,            tmotorServoContinuousRotation, openLoop, driveLeft, encoderPort, dgtl1)
#pragma config(Motor,  port8,           BR,            tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          FL,            tmotorVex269_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task write(){
int lef = motor[FL];
int rig = motor[FR];
if(lef > 10 || lef < -10){
	writeDebugStreamLine("motor[BL] = %d", lef,";");
	writeDebugStreamLine("motor[FL] = %d", lef,";");}
if(rig > 10 || rig < -10){
	writeDebugStreamLine("motor[BR] = %d", rig,";");
	writeDebugStreamLine("motor[FR] = %d", rig,";");}
writeDebugStreamLine("waitInMilliseconds(100);");
waitInMilliseconds(100);}

task main(){
	clearDebugStream();
	while(true){
		motor[FR] = vexRT(Ch2);
		motor[FL] = vexRT(Ch3);
		motor[BL] = vexRT(Ch3);
		motor[BR] = vexRT(Ch2);
		startTask(write);
		}
	}
