#pragma config(UART_Usage, UART1, VEX_2x16_LCD, baudRate19200, IOPins, None, None)
#pragma config(Sensor, dgtl1,  lft,            sensorQuadEncoder)
#pragma config(Motor,  port1,           FR,            tmotorVex269_HBridge, openLoop)
#pragma config(Motor,  port7,           BL,            tmotorServoContinuousRotation, openLoop, driveLeft, encoderPort, dgtl1)
#pragma config(Motor,  port8,           BR,            tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          FL,            tmotorVex269_HBridge, openLoop)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include <rerun write.c>
#include <rerun read.c>
int x;
int Userinput(){
	while(true){
		if(nLCDButtons == 1){
			return 1;
			}if(nLCDButtons == 4){
			return 2;
		}
	}
}

task main()
{ // Backlight on
    bLCDBacklight = true;
    while( true )
        {
        // toggle code
        displayLCDCenteredString(0, "Side?");
				displayLCDString(0, 0, "Write      Read");
				x = Userinput();
			if(x == 1){
				starttask()}



        }
}
