#pragma config(Motor,  port1,           FrontRight,    tmotorVex393, openLoop)
#pragma config(Motor,  port2,           FrontLeft,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           BackRight,     tmotorVex393, openLoop)
#pragma config(Motor,  port4,           BackLeft,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           LiftTopRight,  tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           LiftTopLeft,   tmotorVex393, openLoop)
#pragma config(Motor,  port7,           LiftBottomRight, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           LiftBottomLeft, tmotorVex393, openLoop)
#pragma config(Motor,  port9,           LoaderRght,    tmotorVex269, openLoop)
#pragma config(Motor,  port10,          LoaderLeft,    tmotorVex269, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	while(true){

		if(vexRT(Btn6U) == 1){
			startMotor(LiftTopRight, 100);
			startMotor(LiftTopLeft, 100);
			startMotor(LiftBottomRight, 100);
			startMotor(LiftBottomLeft, 100);
		}
		if(vexRT(Btn6D) == 1){
			startMotor(LiftTopRight, -100);
			startMotor(LiftTopLeft, -100);
			startMotor(LiftBottomRight, -100);
			startMotor(LiftBottomLeft, -100);
		}
		startMotor(FrontLeft, vexRT(Ch3));
		startMotor(BackLeft, vexRT(Ch3));
		startMotor(FrontRight, vexRT(Ch2));
		startMotor(BackLeft, vexRT(Ch2));
		waitInMilliseconds (10);
		stopMotor(FrontLeft);
		stopMotor(BackLeft);
		stopMotor(FrontRight);
		stopMotor(BackRight);

		startMotor(FrontLeft, (-vexRT(AccelX)));
		startMotor(FrontRight, (vexRT(AccelX)));
		startMotor(BackLeft, (vexRT(AccelX)));
		startMotor(BackRight, (-vexRT(AccelX)));

		stopMotor(LiftTopRight);
		stopMotor(LiftTopLeft);
		stopMotor(LiftBottomRight);
		stopMotor(LiftBottomLeft);
	}
}
