#pragma config(Sensor, in1,    zAccel,         sensorAccelerometer)
#pragma config(Sensor, in2,    yAccel,         sensorAccelerometer)
#pragma config(Sensor, in3,    xAccel,         sensorAccelerometer)
#pragma config(Sensor, dgtl4,  lif,            sensorQuadEncoder)
#pragma config(Motor,  port1,           liftleft,      tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           backright,     tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port3,           frontright,    tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port4,           liftleft2,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           RightClaw,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port6,           LeftClaw,      tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           liftright2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           liftright,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           backleft,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port10,          frontleft,     tmotorVex393_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void lift(int time, string direction){
	if (direction == "up"){
		motor[liftleft] = (127*(0.9));
		motor[liftright] = (127*(0.9));
		motor[liftleft2] = (127*(0.9));
		motor[liftright2] = (127*(0.9));
		waitInMilliseconds(time);
		stopMotor(liftleft);
		stopMotor(liftright);
		stopMotor(liftleft2);
		stopMotor(liftright2);}
	if (direction == "down"){
		motor[liftleft] = (-127*(0.9));
		motor[liftright] = (-127*(0.9));
		motor[liftleft2] = (-127*(0.9));
		motor[liftright2] = (-127*(0.9));
		waitInMilliseconds(time);
		stopMotor(liftleft);
		stopMotor(liftright);
		stopMotor(liftleft2);
		stopMotor(liftright2);}
}
string up = "up", down = "down";
task main(){
	while(true){
		motor[frontleft] = vexRT(Ch3);
		motor[backleft] = vexRT(Ch3);
		motor[frontright] = vexRT(Ch2);
		motor[backright] = vexRT(Ch2);
		waitInMilliseconds(10);
		stopMotor(frontleft);
		stopMotor(backleft);
		stopMotor(frontright);
		stopMotor(backright);

		if(vexRT(Btn6U) == 1){
			lift(10, up);}

		if(vexRT(Btn6D) == 1){
			lift(10, down);}

		if(vexRT[Btn5U] == 1){
			setServo(LeftClaw, 127);
			setServo(RightClaw, -127);}

		else if(vexRT[Btn5D] == 1){////////////////////////////claw//////////////////////
			setServo(LeftClaw, -120);
			setServo(RightClaw,120);}

		else{
			setServo(RightClaw, 0);
			setServo(LeftClaw, 0);}
	}

}
