#pragma config(Motor,  port1,           LM,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           RM,            tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



void move(int go, string direction){
	if(direction == "forward"){
		startMotor (LM, 127);
		startMotor (RM, 127);
		waitInMilliseconds(go);
		stopMotor(LM);
		stopMotor(RM);}
	if(direction == "backward"){
		startMotor (LM, -127);
		startMotor (RM, -127);
		waitInMilliseconds(go);//uiutgluy//
		stopMotor(LM);
		stopMotor(RM);}
}
task main(){
}
