#pragma config(Motor,  port1,           motor1,        tmotorVex269_HBridge, openLoop)
#pragma config(Motor,  port2,           motor2,        tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           motor3,        tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port4,           motor4,        tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main{
	while(true){
		startMotor(motor1, (-vexRT(AccelX) - vexRT(AccelY)));
		startMotor(motor2, (-vexRT(AccelX) + vexRT(AccelY)));
		startMotor(motor3, (vexRT(AccelX) + vexRT(AccelY)));
		startMotor(motor4, (vexRT(AccelX) - vexRT(AccelY)));


	}
}
