#pragma config(Motor,  port1,           leftmotor,     tmotorVex393, openLoop)
#pragma config(Motor,  port10,          rightmotor,    tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
while(true){
		startMotor (leftmotor, vexRT(Ch3));
		startMotor (rightmotor, vexRT(Ch2));
		waitInMilliseconds (10);
		stopMotor (leftmotor);
		stopMotor (rightmotor);
	}
}
