#pragma config(Motor,  port1,           leftlift,      tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port10,          rightlift,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	while(true){

		if(vexRT(Btn5U) == 1){
			motor[leftlift] = (127 * .7);
			motor[rightlift] = (127 * .7);
			waitInMilliseconds(10);
			stopMotor(leftlift);
			stopMotor(rightlift);}
		if(vexRT(Btn5D) == 1){
			motor[leftlift] = (-127 * .7);
			motor[rightlift] = (-127 * .7);
			waitInMilliseconds(10);
			stopMotor(leftlift);
			stopMotor(rightlift);}


	}
}
